-- tables
CREATE
    TABLE
        IF NOT EXISTS AIRBYTE_CONFIGS(
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            config_id VARCHAR(36) NOT NULL,
            config_type VARCHAR(60) NOT NULL,
            config_blob JSONB NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );


create table "public"."state"(
  "id" uuid not null,
  "connection_id" uuid not null,
  "state" jsonb null,
  "created_at" timestamptz(35) not null default null,
  "updated_at" timestamptz(35) not null default null,
  "stream_name" text null,
  "namespace" text null,
  "type" state_type not null default null,
  constraint "state_pkey"
    primary key (
      "id", 
      "connection_id"
    )
);

-- indices
CREATE
    UNIQUE INDEX IF NOT EXISTS airbyte_configs_type_id_idx ON
    AIRBYTE_CONFIGS(
        config_type,
        config_id
    );

CREATE
    INDEX IF NOT EXISTS airbyte_configs_id_idx ON
    AIRBYTE_CONFIGS(config_id);
